# Generated by Django 3.2.16 on 2023-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
