# Generated by Django 3.2.16 on 2023-04-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
